# Challenge 3

In this challenge we will work on the `Orders` data set. In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Business Intelligence Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

## Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [1]:
# import required libraries
import numpy as np
import pandas as pd

Next, extract and import `Orders` dataset into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [2]:
orders = pd.read_csv("Orders.csv")
orders.head()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

In [3]:
# Sub Problem 1: Aggregate the amount_spent for unique customers
customer_expenses = orders.groupby('CustomerID')['amount_spent'].sum()
customer_expenses.head()

CustomerID
12346    77183.60
12347     4310.00
12348     1797.24
12349     1757.55
12350      334.40
Name: amount_spent, dtype: float64

In [4]:
# Sub Problem 2: Select customers whose aggregated amount_spent is in a given quantile range
vip_quantile = customer_expenses.quantile(0.95)
vip_quantile

5840.181999999982

In [5]:
preferred_quantile = customer_expenses.quantile(0.75)
preferred_quantile

1661.64

In [6]:
# Sub Problem 3: Label selected customers as "VIP" or "Preferred"
vip_customers = customer_expenses[customer_expenses > vip_quantile].index.tolist()
vip_customers

[12346,
 12357,
 12359,
 12409,
 12415,
 12428,
 12431,
 12433,
 12435,
 12451,
 12471,
 12472,
 12474,
 12476,
 12477,
 12536,
 12540,
 12557,
 12567,
 12583,
 12590,
 12621,
 12626,
 12637,
 12678,
 12681,
 12682,
 12683,
 12705,
 12709,
 12731,
 12744,
 12748,
 12753,
 12757,
 12766,
 12798,
 12830,
 12901,
 12921,
 12931,
 12939,
 12971,
 12980,
 12989,
 13001,
 13018,
 13027,
 13078,
 13081,
 13089,
 13090,
 13093,
 13097,
 13098,
 13102,
 13113,
 13199,
 13209,
 13225,
 13263,
 13316,
 13319,
 13324,
 13340,
 13408,
 13418,
 13458,
 13488,
 13534,
 13576,
 13629,
 13668,
 13694,
 13709,
 13767,
 13777,
 13798,
 13854,
 13871,
 13881,
 13969,
 13985,
 14031,
 14051,
 14056,
 14057,
 14060,
 14062,
 14088,
 14096,
 14101,
 14156,
 14194,
 14258,
 14298,
 14367,
 14415,
 14505,
 14527,
 14606,
 14607,
 14646,
 14667,
 14680,
 14733,
 14735,
 14769,
 14796,
 14849,
 14866,
 14895,
 14911,
 14936,
 14944,
 14952,
 14961,
 15005,
 15023,
 15039,
 15044,
 15061,
 15078,
 15098,
 15125,
 15144,
 15159,
 15189,
 15194,
 15249,
 15251,
 15290,
 15311,
 15358,
 15382,
 15465,
 15482,
 15498,
 15502,
 15513,
 15601,
 15615,
 15640,
 15694,
 15749,
 15769,
 15838,
 15856,
 15939,
 16000,
 16013,
 16029,
 16033,
 16126,
 16133,
 16180,
 16182,
 16187,
 16210,
 16333,
 16353,
 16422,
 16446,
 16523,
 16525,
 16532,
 16558,
 16652,
 16656,
 16672,
 16684,
 16705,
 16713,
 16729,
 16745,
 16746,
 16779,
 16814,
 16839,
 16843,
 16873,
 16923,
 17017,
 17107,
 17139,
 17243,
 17306,
 17315,
 17338,
 17340,
 17381,
 17389,
 17396,
 17404,
 17416,
 17428,
 17450,
 17509,
 17511,
 17581,
 17675,
 17677,
 17706,
 17735,
 17811,
 17841,
 17857,
 17865,
 17949,
 18055,
 18092,
 18102,
 18109,
 18139,
 18172,
 18223,
 18229]

In [7]:
preferred_customers = customer_expenses[(customer_expenses > preferred_quantile) & 
                                        (customer_expenses <= vip_quantile)].index.tolist()
preferred_customers

[12347,
 12348,
 12349,
 12352,
 12356,
 12360,
 12362,
 12370,
 12371,
 12378,
 12380,
 12381,
 12383,
 12388,
 12395,
 12397,
 12405,
 12406,
 12407,
 12408,
 12417,
 12423,
 12424,
 12429,
 12432,
 12437,
 12438,
 12444,
 12449,
 12454,
 12455,
 12456,
 12457,
 12473,
 12480,
 12481,
 12483,
 12484,
 12490,
 12500,
 12501,
 12502,
 12517,
 12518,
 12520,
 12523,
 12524,
 12528,
 12530,
 12539,
 12553,
 12560,
 12562,
 12569,
 12578,
 12584,
 12585,
 12594,
 12597,
 12598,
 12600,
 12610,
 12613,
 12615,
 12619,
 12625,
 12627,
 12633,
 12635,
 12643,
 12645,
 12647,
 12653,
 12656,
 12662,
 12664,
 12668,
 12669,
 12670,
 12674,
 12684,
 12685,
 12688,
 12700,
 12704,
 12708,
 12712,
 12714,
 12720,
 12721,
 12726,
 12727,
 12747,
 12749,
 12752,
 12754,
 12755,
 12758,
 12762,
 12764,
 12779,
 12782,
 12783,
 12823,
 12836,
 12839,
 12840,
 12841,
 12843,
 12853,
 12856,
 12867,
 12876,
 12906,
 12909,
 12910,
 12912,
 12913,
 12916,
 12928,
 12935,
 12948,
 12949,
 12950,
 12955,
 12957,
 12963,
 13004,
 13012,
 13013,
 13014,
 13015,
 13021,
 13047,
 13048,
 13050,
 13069,
 13082,
 13094,
 13115,
 13124,
 13126,
 13134,
 13135,
 13136,
 13137,
 13139,
 13141,
 13148,
 13149,
 13157,
 13162,
 13174,
 13178,
 13183,
 13184,
 13196,
 13198,
 13224,
 13230,
 13246,
 13265,
 13266,
 13267,
 13268,
 13269,
 13285,
 13297,
 13305,
 13317,
 13327,
 13334,
 13344,
 13362,
 13365,
 13373,
 13381,
 13384,
 13394,
 13421,
 13422,
 13426,
 13435,
 13437,
 13448,
 13450,
 13451,
 13456,
 13468,
 13471,
 13481,
 13495,
 13505,
 13507,
 13510,
 13517,
 13520,
 13523,
 13527,
 13536,
 13552,
 13555,
 13562,
 13564,
 13571,
 13577,
 13588,
 13590,
 13593,
 13599,
 13630,
 13631,
 13632,
 13644,
 13647,
 13650,
 13654,
 13658,
 13680,
 13685,
 13695,
 13700,
 13704,
 13722,
 13725,
 13735,
 13742,
 13755,
 13756,
 13758,
 13763,
 13769,
 13771,
 13784,
 13802,
 13804,
 13808,
 13815,
 13824,
 13831,
 13842,
 13851,
 13862,
 13868,
 13869,
 13870,
 13875,
 13880,
 13883,
 13890,
 13895,
 13901,
 13908,
 13911,
 13924,
 13941,
 13949,
 13952,
 13953,
 13971,
 13975,
 13982,
 13983,
 13988,
 13993,
 13994,
 13999,
 14001,
 14004,
 14005,
 14016,
 14030,
 14032,
 14040,
 14049,
 14085,
 14092,
 14099,
 14107,
 14110,
 14112,
 14113,
 14121,
 14125,
 14132,
 14135,
 14145,
 14146,
 14159,
 14163,
 14175,
 14180,
 14188,
 14189,
 14191,
 14209,
 14210,
 14211,
 14215,
 14216,
 14217,
 14221,
 14226,
 14227,
 14232,
 14235,
 14239,
 14243,
 14245,
 14250,
 14251,
 14257,
 14262,
 14277,
 14282,
 14285,
 14286,
 14290,
 14291,
 14292,
 14299,
 14305,
 14306,
 14307,
 14309,
 14315,
 14329,
 14334,
 14341,
 14360,
 14364,
 14387,
 14388,
 14390,
 14395,
 14397,
 14401,
 14407,
 14408,
 14409,
 14418,
 14422,
 14426,
 14432,
 14439,
 14440,
 14441,
 14456,
 14459,
 14461,
 14462,
 14466,
 14472,
 14482,
 14493,
 14498,
 14502,
 14503,
 14506,
 14515,
 14524,
 14525,
 14530,
 14533,
 14534,
 14535,
 14543,
 14544,
 14546,
 14547,
 14554,
 14560,
 14562,
 14565,
 14572,
 14595,
 14608,
 14621,
 14626,
 14639,
 14640,
 14653,
 14655,
 14659,
 14665,
 14673,
 14676,
 14688,
 14691,
 14696,
 14700,
 14701,
 14702,
 14709,
 14711,
 14713,
 14730,
 14732,
 14739,
 14755,
 14766,
 14776,
 14800,
 14808,
 14810,
 14825,
 14828,
 14834,
 14841,
 14842,
 14844,
 14852,
 14854,
 14868,
 14887,
 14903,
 14907,
 14930,
 14934,
 14935,
 14978,
 15021,
 15032,
 15033,
 15034,
 15046,
 15050,
 15058,
 15065,
 15067,
 15089,
 15093,
 15105,
 15113,
 15114,
 15123,
 15129,
 15140,
 15150,
 15152,
 15157,
 15179,
 15187,
 15195,
 15203,
 15218,
 15220,
 15228,
 15235,
 15240,
 15241,
 15245,
 15260,
 15267,
 15270,
 15271,
 15281,
 15288,
 15291,
 15296,
 15298,
 15299,
 15301,
 15321,
 15341,
 15351,
 15356,
 15365,
 15367,
 15370,
 15372,
 15373,
 15379,
 15380,
 15394,
 15410,
 15416,
 15443,
 15473,
 15484,
 15485,
 15491,
 15493,
 15505,
 15514,
 15518,
 15521,
 15527,
 15529,
 15531,
 15544,
 15547,
 15549,
 15555,
 15570,
 15572,
 15581,
 15594,
 15606,
 15622,
 15628,
 15632,
 15641,
 15665,
 15671,
 15673,
 15674,
 15676,
 15687,
 15696,
 15704,
 15708,
 15719,
 15722,
 15727,
 15738,
 15750,
 15752,
 15755,
 15764,
 15782,
 15785,
 15786,
 15796,
 15797,
 15804,
 15805,
 15808,
 15811,
 15812,
 15814,
 15815,
 15819,
 15827,
 15834,
 15845,
 15854,
 15861,
 15864,
 15867,
 15874,
 15903,
 15932,
 15947,
 15950,
 15955,
 15971,
 15974,
 15980,
 15981,
 15984,
 15993,
 15998,
 16003,
 16007,
 16011,
 16019,
 16041,
 16057,
 16076,
 16081,
 16098,
 16102,
 16107,
 16115,
 16128,
 16131,
 16143,
 16145,
 16150,
 16152,
 16153,
 16156,
 16161,
 16168,
 16169,
 16170,
 16186,
 16191,
 16201,
 16209,
 16218,
 16240,
 16241,
 16242,
 16249,
 16253,
 16255,
 16258,
 16265,
 16281,
 16293,
 16303,
 16308,
 16316,
 16326,
 16327,
 16341,
 16358,
 16359,
 16360,
 16379,
 16380,
 16393,
 16398,
 16401,
 16407,
 16409,
 16426,
 16440,
 16455,
 16456,
 16458,
 16474,
 16477,
 16497,
 16549,
 16550,
 16553,
 16556,
 16570,
 16592,
 16607,
 16609,
 16618,
 16626,
 16628,
 16633,
 16638,
 16655,
 16670,
 16671,
 16678,
 16681,
 16686,
 16698,
 16700,
 16701,
 16709,
 16710,
 16712,
 16717,
 16719,
 16722,
 16735,
 16743,
 16751,
 16754,
 16764,
 16767,
 16771,
 16775,
 16782,
 16791,
 16813,
 16818,
 16837,
 16841,
 16871,
 16875,
 16902,
 16904,
 16905,
 16912,
 16919,
 16928,
 16931,
 16938,
 16940,
 16942,
 16945,
 16954,
 16966,
 16979,
 16983,
 16984,
 16985,
 16986,
 17001,
 17015,
 17043,
 17049,
 17050,
 17059,
 17061,
 17068,
 17069,
 17071,
 17082,
 17084,
 17086,
 17088,
 17090,
 17091,
 17092,
 17131,
 17133,
 17147,
 17152,
 17160,
 17162,
 17164,
 17173,
 17183,
 17188,
 17191,
 17193,
 17203,
 17211,
 17213,
 17218,
 17220,
 17228,
 17230,
 17231,
 17238,
 17272,
 17282,
 17293,
 17313,
 17314,
 17317,
 17337,
 17346,
 17353,
 17364,
 17365,
 17368,
 17377,
 17386,
 17400,
 17402,
 17406,
 17419,
 17422,
 17426,
 17434,
 17442,
 17444,
 17449,
 17451,
 17457,
 17463,
 17469,
 17490,
 17491,
 17504,
 17512,
 17519,
 17528,
 17530,
 17554,
 17567,
 17576,
 17589,
 17591,
 17593,
 17596,
 17597,
 17602,
 17611,
 17612,
 17613,
 17625,
 17629,
 17634,
 17644,
 17648,
 17651,
 17652,
 17655,
 17656,
 17659,
 17663,
 17667,
 17669,
 17672,
 17679,
 17682,
 17685,
 17686,
 17690,
 17696,
 17700,
 17702,
 17705,
 17716,
 17719,
 17722,
 17723,
 17725,
 17728,
 17730,
 17738,
 17739,
 17744,
 17750,
 17754,
 17757,
 17758,
 17768,
 17769,
 17787,
 17790,
 17799,
 17809,
 17813,
 17819,
 17827,
 17828,
 17838,
 17846,
 17850,
 17858,
 17861,
 17863,
 17870,
 17873,
 17920,
 17924,
 17930,
 17937,
 17940,
 17954,
 17965,
 17975,
 17997,
 18008,
 18041,
 18044,
 18061,
 18065,
 18069,
 18073,
 18075,
 18077,
 18079,
 18087,
 18093,
 18094,
 18097,
 18118,
 18122,
 18144,
 18145,
 18173,
 18179,
 18180,
 18188,
 18198,
 18204,
 18210,
 18219,
 18225,
 18226,
 18230,
 18231,
 18235,
 18241,
 18242,
 18245,
 18251,
 18257,
 18259,
 18260,
 18272,
 18283,
 18287]

In [8]:
def classify_customer(amount_spent):
    if amount_spent > vip_quantile:
        return 'VIP'
    elif amount_spent > preferred_quantile:
        return 'Preferred'
    else:
        return 'Regular'

In [9]:
customer_classification = customer_expenses.apply(classify_customer)
customer_classification.value_counts()

amount_spent
Regular      3254
Preferred     868
VIP           217
Name: count, dtype: int64

In [11]:
customer_classification = customer_classification.rename("Customer_Classification")

In [12]:
orders_with_classification = orders.merge(customer_classification, left_on='CustomerID', right_index=True, how='left')
orders_with_classification

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,Customer_Classification
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,Preferred
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,Preferred
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,Preferred
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,Preferred
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,Preferred
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397919,541904,581587,22613,2011,12,5,12,pack of 20 spaceboy napkins,12,2011-12-09 12:50:00,0.85,12680,France,10.20,Regular
397920,541905,581587,22899,2011,12,5,12,children's apron dolly girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60,Regular
397921,541906,581587,23254,2011,12,5,12,childrens cutlery dolly girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60,Regular
397922,541907,581587,23255,2011,12,5,12,childrens cutlery circus parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60,Regular
397923,541908,581587,22138,2011,12,5,12,baking set 9 piece retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85,Regular

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

## Q2: How to identify which country has the most VIP Customers?

In [18]:
# Filter orders by Customer_Classification = VIP
# Group by Country
# Order by number of unique customers
# Limit 1

country_max_vip = (
    orders_with_classification[orders_with_classification['Customer_Classification']=='VIP']
    .groupby('Country')['CustomerID']
    .nunique()
    .sort_values(ascending=False)
    .head(1)
)
country_max_vip

print(f'{country_max_vip.index[0]} has the most VIP Customers with total number of {country_max_vip.values[0]} customers')

United Kingdom has the most VIP Customers with total number of 177 customers

## Q3: How to identify which country has the most VIP+Preferred Customers combined?

In [24]:
country_max_vip_preferred = (
    orders_with_classification[(orders_with_classification['Customer_Classification']=='VIP') | 
                              (orders_with_classification['Customer_Classification']=='Preferred')]
    .groupby('Country')['CustomerID']
    .nunique()
    .sort_values(ascending=False)
    .head(1)
)
country_max_vip_preferred

print(f'{country_max_vip_preferred.index[0]} has the most VIP+Preferred Customers with total number of {country_max_vip_preferred.values[0]} customers')

United Kingdom has the most VIP+Preferred Customers with total number of 932 customers